const emptyCompany = { name: '', website: '', headquarters: '', industry: '', description: '', fitReasons: [''], objectivesMatched: [''], evidenceUrls: [''], confidence: 'medium', notes: '' };
const starterCompanies = [{ name: 'Sample Mobility AI Ltd', website: 'https://example.com', headquarters: 'London, UK', industry: 'Transport technology', description: 'Example record showing the JSON shape expected after Codex researches companies online.', fitReasons: ['UK-based', 'Builds software for transport operators', 'Has public evidence of deployments'], objectivesMatched: ['Find B2B transport tech suppliers', 'Prioritize companies with clear public traction'], evidenceUrls: ['https://example.com/about', 'https://example.com/case-studies'], confidence: 'medium', notes: 'Replace this with sourced findings.' }];
let brief = { industry: 'Transport technology', location: 'United Kingdom', objectives: 'Find companies building software, data platforms, AI, fleet, logistics, rail, bus, micromobility, or infrastructure tools. Prioritize B2B vendors with public evidence.', mustHave: 'Company name, website, HQ/location, short description, why it matches, source URLs.', exclude: 'Pure consultancies with no product; inactive companies; companies without a useful web presence.', maxResults: 25 };
let companies = starterCompanies;
let jsonText = JSON.stringify(starterCompanies, null, 2);
let message = '';

const app = document.getElementById('app');
const esc = value => String(value ?? '').replace(/[&<>"]/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[ch]));
const promptText = () => `Find companies matching this brief and return only valid JSON matching the schema below.\n\nIndustry: ${brief.industry}\nLocation: ${brief.location}\nObjectives: ${brief.objectives}\nMust include: ${brief.mustHave}\nExclude: ${brief.exclude}\nMaximum results: ${brief.maxResults}\n\nResearch online. Use multiple search queries and cite evidence URLs for each company. Prefer official company pages, credible directories, news, funding databases, and public case studies.\n\nJSON schema:\n[\n  {\n    "name": "Company name",\n    "website": "https://...",\n    "headquarters": "City, Country",\n    "industry": "Specific category",\n    "description": "1-2 sentence summary",\n    "fitReasons": ["reason tied to brief"],\n    "objectivesMatched": ["objective satisfied"],\n    "evidenceUrls": ["https://source-1", "https://source-2"],\n    "confidence": "high|medium|low",\n    "notes": "Optional caveats"\n  }\n]`;
const normalize = company => ({ ...emptyCompany, ...company, fitReasons: Array.isArray(company.fitReasons) ? company.fitReasons : [], objectivesMatched: Array.isArray(company.objectivesMatched) ? company.objectivesMatched : [], evidenceUrls: Array.isArray(company.evidenceUrls) ? company.evidenceUrls : [] });
const setMessage = text => { message = text; render(); if (text) setTimeout(() => { message = ''; render(); }, 1800); };

function render() {
  app.innerHTML = `<section class="hero"><div><p class="eyebrow">Codex company research workspace</p><h1>Find, structure, and review matching companies</h1><p>Describe an industry, location, and objectives. Copy the generated research prompt to Codex, paste its JSON back here, then browse, edit, and export the company list.</p></div><div class="heroIcon">🏢</div></section>
  <section class="grid two"><div class="panel"><h2><span>🔎</span> Research brief</h2>${briefFields()}</div><div class="panel"><h2><span>📋</span> Codex prompt</h2><textarea class="prompt" readonly>${esc(promptText())}</textarea><div class="actions"><button data-action="copyPrompt">📋 Copy prompt</button><button data-action="syncJson">🧾 Sync JSON editor</button></div>${message ? `<p class="message">${esc(message)}</p>` : ''}</div></section>
  <section class="panel"><h2><span>⬆️</span> Paste researched JSON</h2><textarea class="jsonbox" id="jsonText">${esc(jsonText)}</textarea><div class="actions"><button data-action="importJson">⬆️ Import JSON</button><button data-action="downloadJson">⬇️ Download JSON</button><button data-action="copyJson">🧾 Copy current JSON</button></div></section>
  <section class="toolbar"><h2>Company results (${companies.length})</h2><button data-action="addCompany">➕ Add company</button></section><section class="cards">${companies.map(companyCard).join('')}</section>`;
}
function briefFields() { return [['industry','Industry'], ['location','Location'], ['objectives','Objectives'], ['mustHave','Must include'], ['exclude','Exclude']].map(([key,label]) => `<label>${label}<textarea data-brief="${key}" rows="${key === 'objectives' ? 4 : 2}">${esc(brief[key])}</textarea></label>`).join('') + `<label>Maximum results<input data-brief="maxResults" type="number" min="1" max="100" value="${esc(brief.maxResults)}"></label>`; }
function companyCard(company, index) { return `<article class="card"><div class="cardHead"><input class="name" data-company="${index}" data-key="name" placeholder="Company name" value="${esc(company.name)}"><button class="ghost" data-action="removeCompany" data-index="${index}">🗑️</button></div><div class="fields">${['website','headquarters','industry'].map(k => `<label>${k[0].toUpperCase()+k.slice(1)}<input data-company="${index}" data-key="${k}" value="${esc(company[k])}"></label>`).join('')}<label>Confidence<select data-company="${index}" data-key="confidence">${['high','medium','low'].map(v => `<option ${company.confidence === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label></div>${textArea(index,'description','Description',company.description)}${textArea(index,'fitReasons','Fit reasons (one per line)',company.fitReasons.join('\n'), true)}${textArea(index,'objectivesMatched','Objectives matched (one per line)',company.objectivesMatched.join('\n'), true)}${textArea(index,'evidenceUrls','Evidence URLs (one per line)',company.evidenceUrls.join('\n'), true)}<div class="links">${company.evidenceUrls.map((url,i) => `<a href="${esc(url)}" target="_blank" rel="noreferrer">Source ${i+1} ↗</a>`).join('')}</div>${textArea(index,'notes','Notes',company.notes)}</article>`; }
function textArea(i,k,label,value,list=false) { return `<label>${label}<textarea data-company="${i}" data-key="${k}" ${list ? 'data-list="true"' : ''}>${esc(value)}</textarea></label>`; }

app.addEventListener('input', event => { const t = event.target; if (t.dataset.brief) brief[t.dataset.brief] = t.value; if (t.id === 'jsonText') jsonText = t.value; if (t.dataset.company) { const value = t.dataset.list ? t.value.split('\n').map(v => v.trim()).filter(Boolean) : t.value; companies[Number(t.dataset.company)][t.dataset.key] = value; } });
app.addEventListener('click', async event => { const button = event.target.closest('button'); if (!button) return; const action = button.dataset.action; if (action === 'copyPrompt') { await navigator.clipboard.writeText(promptText()); setMessage('Copied prompt to clipboard.'); } if (action === 'syncJson') { jsonText = JSON.stringify(companies, null, 2); setMessage('JSON editor synced from cards.'); } if (action === 'copyJson') { await navigator.clipboard.writeText(JSON.stringify(companies, null, 2)); setMessage('Copied current JSON.'); } if (action === 'downloadJson') { const blob = new Blob([JSON.stringify(companies, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = Object.assign(document.createElement('a'), { href: url, download: 'company-findings.json' }); a.click(); URL.revokeObjectURL(url); } if (action === 'importJson') { try { const parsed = JSON.parse(jsonText); if (!Array.isArray(parsed)) throw new Error('Top-level JSON must be an array.'); companies = parsed.map(normalize); setMessage(`Imported ${parsed.length} companies.`); } catch (error) { setMessage(`Import failed: ${error.message}`); } } if (action === 'addCompany') { companies.push({ ...emptyCompany }); render(); } if (action === 'removeCompany') { companies.splice(Number(button.dataset.index), 1); render(); } });
render();
